name: Build workflow

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update submodules
      id: update
      run: git submodule update --remote --recursive

    - name: Run rebuild script
      run: |
        cd ${GITHUB_WORKSPACE}/script
        rebuild_libs_windows.cmd cmake
        cd ${GITHUB_WORKSPACE}
